title: My Site
description: My existing site + new Jekyll pages
# theme: jekyll-theme-slate (for .md files, not .html ?)
# https://pages-themes.github.io/slate/
# https://chatgpt.com/c/67f4016e-8f28-800f-8361-55d067baed19