title: trycholog.pl
description: Trychologiczna wiedza o włosach, łysieniu androgenowym, minoxidilu, DHT i przyczynach wypadania włosów.
url: "https://trycholog.pl"
lang: "pl-PL"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

twitter:
  card: summary

defaults:
  - scope:
      path: ""
    values:
      image: /favicon.png
      author: trycholog.pl
      locale: pl_PL
